server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  h2:
    console:
      enabled: true
  flyway:
    init-sqls: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        type: trace
        ddl-auto: update
        show_sql: false
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
